name: E2E Testing

on: 
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run build
          start: pnpm run preview
          wait-on: http://localhost:4173
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
