name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run build
          start: pnpm run preview
          browser: chrome
