name: Unit Testing

on: 
  push:
    branches: [main]

jobs:
  vitest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: true
      - name: Run unit tests
        run: pnpm run test
